### ISSUE TITLE
It doesn't seem to work

### ISSUE THREAD

**Issue by nathan-code** [badranX/bt-lib#1]
First of all, thank you for the source code. Unfortunately, I have encountered problems in use. I exported jar packages from Java projects to use in unity, but I failed to achieve the expected purpose. Did I miss anything? I hope I can get your help. thank you.

**Comment by badranX** [comment]
I'm sorry the project is a mess. I'll try to clean it later.
 First make sure you got the AndroidManifest.xml in your Plugin folder using the wizard (Tools->Techtweaking->.....->Install). After this delete the generated jar file, then export from java using "gradle".

**Comment by nathan-code** [comment]
> I'm sorry the project is a mess. I'll try to clean it later.
> First make sure you got the AndroidManifest.xml in your Plugin folder using the wizard (Tools->Techtweaking->.....->Install). After this delete the generated jar file, then export from java using "gradle".

Thank you for your reply. I did this according to the document you provided, but unfortunately it didn't work as expected. But using the jar package in unity project can achieve the expected effect, but it cannot be modified.

**Comment by badranX** [comment]
-I think the bug is in this commit: 80eebcf4f33ac76261e1f315731a95f42536e7d9. Revert to any commit before this one and hopefully it will work.
-I'm sorry but it will take me time to look into this. 10 days or more. I'm busy this month.

**Comment by badranX** [comment]
I'm sorry for being all that late. Finally, I did an actual test, instead of speculating. I've tested the latest commit on Unity3d 2018.4.25f1. **The library works as expected!.**

Quoting you: "unfortunately it didn't work as expected". Did anything work? Or you just had some issues?. Also, please give more details on the Unity version and Android device you are using.

Still, I think you had a problem with Gradle setup, so I'll detail it here:
1) From your Unity menu, Tools->Techtweaking->.....->Install.
2) From the terminal, in the "Java_BT_lib" folder, run:
**On Windows:** `gradlew doRelease`
**On Mac or Linux:** `./gradlew doRelease`

doRelease can be replaced by doDebug.

Now you would have a new ".jar" file in your "Plugins/Android".

Note: If you performed "Tools->Techtweaking->.....->Install" again, it will replace your ".jar" with the one provided with the library (which is available inside "NativeLibraries" folder ).
